version: 2.1
commands:
  welcome:
    description: "welcome command"
    steps:
      - run: echo "hello Mr."
jobs:
  hello:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - welcome
      - run:
          name: list
          command: ls
  env:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - welcome
      - run:
         name: print env
         command: echo $test
workflows:
  print name_env:
    jobs:
      - hello
      - env:
         requires:
           - hello
         context: test